import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import AnimatedNumbersOverlay from "@/components/severanceBg";
import FloatingNavigation from "@/components/FloatingNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const scriptorama = localFont({
  src: "./fonts/ScriptoramaTradeshowJFRegular.ttf",
  variable: "--font-scriptorama",
  display: "swap",
});

const manifold = localFont({
  src: [
    {
      path: "./fonts/Fontspring-DEMO-manifoldextendedcf-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Fontspring-DEMO-manifoldextendedcf-bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-manifold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${scriptorama.variable} ${manifold.variable} antialiased`}
      >
        <AnimatedNumbersOverlay />
        <FloatingNavigation />
        {children}
      </body>
    </html>
  );
}
